spring:
  application:
    name: socket
  profiles:
    active: local
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

